version: "3"
services:
  phpstorm:
    container_name: truckpad_phpstorm
    build:
      context: docker/php
    environment:
      APP_ENV: local
      DB_CONNECTION: mysql
      DB_HOST: 176.70.1.3
      DB_PORT: 3306
      DB_DATABASE: truckpad
      DB_USERNAME: root
      DB_PASSWORD: secret
    volumes:
      - truckpad:/opt/truckpad:nocopy,delegated
    networks:
      - default
volumes:
  truckpad:
    external: true


