<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Faker\Generator;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;
    
    protected Generator $faker;
    
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->faker = $this->app->make(Generator::class);
    }
}
